### ISSUE TITLE
No symbols returned

### ISSUE THREAD

**Issue by tmarplatt** [savetheclocktower/pulsar-ide-d#1]
- Pulsar v1.123.0 (AppImage)
- serve-d v0.7.6 with workspace-d v3.7.0
- On Linux Mint 22 Cinnamon

After installing serve-d and this pulsar package, regardless of project or file being open, no symbol is being detected. `symbols-view` just shows an empty symbol list.

No errors in console. The `serve-d` process, spawned by pulsar, is running in the background.

My provider list (copied from Symbols View Redux providers):

* **ctags** provided by `symbol-provider-ctags`
* **Tree-sitter** provided by `symbol-provider-tree-sitter`
* **serve-d** provided by `pulsar-ide-d`

What could be happening here?

**Comment by savetheclocktower** [comment]
I was able to verify that `serve-d` was giving me symbols yesterday when I was sanity-checking the extension, so I'm not sure why this could be happening.

Try going to the `symbols-view` settings and adding `pulsar-ide-d` in the “Prefer Certain Providers” field, then reload the window for safety's sake. If that still doesn't fix it, reply with some sample code that exhibits the problem and I'll see if I can reproduce it.

**Comment by savetheclocktower** [comment]
Also, you can check “Enable Debug Logging” in the `symbols-view` settings to see more stuff in the dev tools console. Maybe that'll tell you something about which provider is being chosen.

**Comment by tmarplatt** [comment]
It seems to be a misconfiguration issue. Here is the console output 

```
logger.ts:19 D (serve-d) stderr serve-d v0.7.6 with workspace-d v3.7.0
logger.ts:19 D (serve-d) stderr Included features: "d", "workspaces"
logger.ts:19 D (serve-d) stderr Built: Sun Jan  7 16:11:39 2024
logger.ts:19 D (serve-d) stderr with compiler LDC v2.106 on linux littleEndian
logger.ts:19 D (serve-d) stderr dub, dfmt and dscanner are bundled within (compiled in)
logger.ts:19 D (serve-d) stderr 2024-12-02T16:17:47.177 [error] extension.d:342:validateConfigurationItemsResponse Got invalid configuration response from language client. (not an array)
logger.ts:19 D (serve-d) stderr 2024-12-02T16:17:47.177 [error] extension.d:461:__lambda6 Syncing user configuration failed!
logger.ts:19 D (serve-d) stderr 2024-12-02T16:17:47.177 [warning
logger.ts:19 D (serve-d) stderr ] extension.d:463:__lambda6 Didn't receive any configuration notification, manually requesting all configurations now
logger.ts:19 D (serve-d) stderr 2024-12-02T16:17:47.188 [error] extension.d:342:validateConfigurationItemsResponse Got invalid configuration response from language client. (not an array)
```

**Comment by savetheclocktower** [comment]
So one thing to try would be to download `serve-d` version `v0.8.0-beta.18`; that's the version I tested against.

Still, it's not immediately obvious to me why this error is happening. It seems to be during the `workspace/configuration` exchange; that's a [highly standardized process](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) during which the client reports its capabilities to the server. It's not often that things go wrong here. (Version `0.7.6` of `serve-d` dates back to January, but the LSP spec doesn't evolve _that_ quickly.)

It seems to be hitting [this code path](https://github.com/Pure-D/serve-d/blob/0339545a7af824206cfd29d1242673f46c2707f1/serverbase/source/served/utils/serverconfig.d#L420-L422), but I'm not sure why. If this issue still occurs after you update `serve-d`, I'd suggest the following:

1. Open the developer console
2. Execute the following line: `atom.config.set('core.debugLSP', true)`
3. Reload the window or relaunch Pulsar
4. Open the console again and filter the console on `workspace/configuration`; the extension should report what it's sending to `serve-d`. If it's invalid, it should look pretty obviously invalid. If you're unsure, you can copy the plaintext of what it's sending or else attach a screenshot.

Sorry for the trouble; my flirtation with D started and ended on the day I created this package. My skill is in being able to turn language servers into useful Pulsar packages, but some language servers are very generic, whereas others assume you have some familiarity with the language in question.

**Comment by tmarplatt** [comment]
It works after updating `serve-d` to latest beta. It prompted me to update DCD. And I'm seeing symbols now.

Thanks!

**Comment by savetheclocktower** [comment]
Happy to see this resolved. I’ll try to remember to update the README to mention a specific version of `serve-d`. Thanks!
